.docker_build_base:
  tags: [trigger]
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  variables:
    DOCKER_BUILDKIT: "1"

.build_template:
  extends: .docker_build_base
  stage: build
  script:
    - |
      docker build \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        --cache-from $CI_REGISTRY_IMAGE:cache \
        --cache-from $CI_REGISTRY_IMAGE:latest \
        -t $IMAGE_TAG \
        ${ADDITIONAL_TAGS:+$(echo $ADDITIONAL_TAGS | tr ',' '\n' | xargs -I {} echo "-t {}")} \
        .
    - docker push $IMAGE_TAG
    - |
      if [ -n "$ADDITIONAL_TAGS" ]; then
        echo "$ADDITIONAL_TAGS" | tr ',' '\n' | while read tag; do
          docker push "$tag"
        done
      fi
    - docker tag $IMAGE_TAG $CI_REGISTRY_IMAGE:cache
    - docker push $CI_REGISTRY_IMAGE:cache

build:test:
  extends: .build_template
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    ADDITIONAL_TAGS: "$CI_REGISTRY_IMAGE:test"

build:prod:
  extends: .build_template
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    ADDITIONAL_TAGS: "$CI_REGISTRY_IMAGE:latest"
