.python_base:
  image: ghcr.io/astral-sh/uv:python3.13-alpine
  tags: [docker]
  before_script:
    - uv sync --frozen --no-cache
  cache:
    key: python-${CI_COMMIT_REF_SLUG}
    paths:
      - .venv/

.node_base:
  image: node:20-alpine
  tags: [docker]
  before_script:
    - cd frontend
    - npm ci
  cache:
    key: node-${CI_COMMIT_REF_SLUG}
    paths:
      - frontend/node_modules/

lint:python:
  extends: .python_base
  stage: validate
  script:
    - echo "Running ruff check..."
    - uvx ruff check --config pyproject.toml ./app
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG

format:python:
  extends: .python_base
  stage: validate
  script:
    - echo "Checking Python formatting..."
    - uvx ruff format --config pyproject.toml --check ./app
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"
  allow_failure: true

lint:frontend:
  extends: .node_base
  stage: validate
  script:
    - echo "Running ESLint..."
    - npm run lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG
  allow_failure: true

typecheck:frontend:
  extends: .node_base
  stage: validate
  script:
    - echo "Running TypeScript type check..."
    - npx tsc --noEmit
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"
  allow_failure: true

test:python:
  extends: .python_base
  stage: test
  script:
    - echo "Running Python tests..."
    - |
      if [ -d "app/tests" ] || [ -d "tests" ]; then
        .venv/bin/pytest -v --tb=short --cov=app --cov-report=xml --cov-report=term-missing
      else
        echo "No tests directory found, skipping..."
      fi
  coverage: '/TOTAL.*\s+(\d+%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"
  allow_failure: true

test:frontend:
  extends: .node_base
  stage: test
  script:
    - echo "Running frontend tests..."
    - |
      if npm run test --if-present 2>/dev/null; then
        echo "Tests completed"
      else
        echo "No test script found, skipping..."
      fi
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"
  allow_failure: true
