FROM rabbitmq:4-management

ADD https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v4.0.2/rabbitmq_delayed_message_exchange-4.0.2.ez /opt/rabbitmq/plugins/

RUN chmod 644 /opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-4.0.2.ez
RUN rabbitmq-plugins enable rabbitmq_delayed_message_exchange
