FROM rabbitmq:4.2-management

COPY ./rabbit_plugins/rabbitmq_delayed_message_exchange-4.2.0.ez /opt/rabbitmq/plugins/

RUN chmod 644 /opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-4.2.0.ez
RUN rabbitmq-plugins enable rabbitmq_delayed_message_exchange
