version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

loggers:
  root:
    level: INFO
    handlers: [console]
    propagate: false

  uvicorn:
    level: INFO
    handlers: [console]
    propagate: false

  uvicorn.error:
    level: INFO
    handlers: [console]
    propagate: false

  uvicorn.access:
    level: WARNING
    handlers: [console]
    propagate: false

  aiogram.event:
    level: WARNING
    handlers: [console]
    propagate: false

  app:
    level: INFO
    handlers: [console]
    propagate: false
