"""add_chat_moderation_and_warns

Revision ID: 00b36600ebfd
Revises: 21738c83d241
Create Date: 2026-01-02 07:29:35.992848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b36600ebfd'
down_revision: Union[str, Sequence[str], None] = '21738c83d241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_warns_chat_id_user_id', 'warns', ['chat_id', 'user_id'], unique=False)
    op.add_column('chats', sa.Column('warn_limit', sa.Integer(), server_default='3', nullable=False))
    op.add_column('chats', sa.Column('warn_punishment', sa.String(length=10), server_default='ban', nullable=False))
    op.add_column('chats', sa.Column('warn_duration', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'warn_duration')
    op.drop_column('chats', 'warn_punishment')
    op.drop_column('chats', 'warn_limit')
    op.drop_index('ix_warns_chat_id_user_id', table_name='warns')
    op.drop_table('warns')
    # ### end Alembic commands ###
