"""add_moderation

Revision ID: 21738c83d241
Revises: c9a278958f56
Create Date: 2025-12-28 16:48:49.381680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21738c83d241'
down_revision: Union[str, Sequence[str], None] = 'c9a278958f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_chats',
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('banned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )

    # Create the enum type explicitly
    moderation_status_enum = sa.Enum('PENDING', 'SAFE', 'FLAGGED', 'BANNED', 'ERROR', name='moderation_status_enum')
    moderation_status_enum.create(op.get_bind())

    op.add_column('triggers', sa.Column('moderation_status', moderation_status_enum, server_default='PENDING', nullable=False))
    op.add_column('triggers', sa.Column('moderation_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('triggers', 'moderation_reason')
    op.drop_column('triggers', 'moderation_status')

    # Drop the enum type explicitly
    moderation_status_enum = sa.Enum('PENDING', 'SAFE', 'FLAGGED', 'BANNED', 'ERROR', name='moderation_status_enum')
    moderation_status_enum.drop(op.get_bind())

    op.drop_table('banned_chats')
    # ### end Alembic commands ###
