"""add_chat_and_user_details

Revision ID: 4bcacdaa0f62
Revises: 52235a2ed1d1
Create Date: 2026-01-10 20:39:31.577296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bcacdaa0f62'
down_revision: Union[str, Sequence[str], None] = '52235a2ed1d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('title', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('username', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('type', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('description', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('invite_link', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('photo_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('language_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'language_code')
    op.drop_column('chats', 'photo_id')
    op.drop_column('chats', 'invite_link')
    op.drop_column('chats', 'description')
    op.drop_column('chats', 'type')
    op.drop_column('chats', 'username')
    op.drop_column('chats', 'title')
    # ### end Alembic commands ###
