"""add timestamps to triggers

Revision ID: 4fca56dde505
Revises: 7d78c30e5434
Create Date: 2026-01-24 04:18:29.683455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fca56dde505'
down_revision: Union[str, Sequence[str], None] = '7d78c30e5434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triggers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('triggers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('triggers', 'updated_at')
    op.drop_column('triggers', 'created_at')
    # ### end Alembic commands ###
