"""add photo_id to user

Revision ID: 65ed9e198d4b
Revises: 57f3061a0d20
Create Date: 2026-01-10 23:34:20.505217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ed9e198d4b'
down_revision: Union[str, Sequence[str], None] = '57f3061a0d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_id')
    # ### end Alembic commands ###
