"""add settings audit log and locked sections

Revision ID: 7a0344c0ace4
Revises: 8d347617535d
Create Date: 2026-04-05 22:47:27.765846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a0344c0ace4'
down_revision: Union[str, Sequence[str], None] = '8d347617535d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_audit_log_chat_id'), 'settings_audit_log', ['chat_id'], unique=False)
    op.add_column('chats', sa.Column('settings_locked_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'settings_locked_sections')
    op.drop_index(op.f('ix_settings_audit_log_chat_id'), table_name='settings_audit_log')
    op.drop_table('settings_audit_log')
    # ### end Alembic commands ###
