"""add_moderation_history

Revision ID: 89610f0651e5
Revises: b5070685a23b
Create Date: 2026-01-30 19:54:21.161789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89610f0651e5'
down_revision: Union[str, Sequence[str], None] = 'b5070685a23b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moderation_history_created_at', 'moderation_history', ['created_at'], unique=False)
    op.create_index('ix_moderation_history_trigger_id', 'moderation_history', ['trigger_id'], unique=False)
    op.alter_column('chat_trust_history', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('chat_trust_history', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('triggers', 'created_by',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('warns', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('warns', 'admin_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warns', 'admin_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('warns', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('triggers', 'created_by',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('chat_trust_history', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('chat_trust_history', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index('ix_moderation_history_trigger_id', table_name='moderation_history')
    op.drop_index('ix_moderation_history_created_at', table_name='moderation_history')
    op.drop_table('moderation_history')
    # ### end Alembic commands ###
