"""add reputation and tag fields

Revision ID: 8d347617535d
Revises: e0b48146dc10
Create Date: 2026-04-05 20:20:09.652584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d347617535d'
down_revision: Union[str, Sequence[str], None] = 'e0b48146dc10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reputation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=False),
    sa.Column('to_user_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'from_user_id', 'to_user_id', 'action_type', 'date', name='uq_reputation_log')
    )
    op.add_column('chats', sa.Column('tags_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('chats', sa.Column('tags_preset', sa.String(length=20), server_default='neutral', nullable=False))
    op.add_column('chats', sa.Column('tags_custom', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chats', sa.Column('tags_weight_reactions', sa.Integer(), server_default='3', nullable=False))
    op.add_column('chats', sa.Column('tags_weight_replies', sa.Integer(), server_default='2', nullable=False))
    op.add_column('chats', sa.Column('tags_weight_messages', sa.Integer(), server_default='1', nullable=False))
    op.add_column('chats', sa.Column('tags_thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chats', sa.Column('tags_daily_message_limit', sa.Integer(), server_default='50', nullable=False))
    op.add_column('chats', sa.Column('tags_daily_reaction_limit', sa.Integer(), server_default='3', nullable=False))
    op.add_column('user_chats', sa.Column('reputation_score', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_chats', sa.Column('reputation_level', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_chats', sa.Column('tag', sa.String(length=16), nullable=True))
    op.add_column('user_chats', sa.Column('tag_is_manual', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_chats', sa.Column('daily_message_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_chats', sa.Column('daily_message_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_chats', 'daily_message_date')
    op.drop_column('user_chats', 'daily_message_count')
    op.drop_column('user_chats', 'tag_is_manual')
    op.drop_column('user_chats', 'tag')
    op.drop_column('user_chats', 'reputation_level')
    op.drop_column('user_chats', 'reputation_score')
    op.drop_column('chats', 'tags_daily_reaction_limit')
    op.drop_column('chats', 'tags_daily_message_limit')
    op.drop_column('chats', 'tags_thresholds')
    op.drop_column('chats', 'tags_weight_messages')
    op.drop_column('chats', 'tags_weight_replies')
    op.drop_column('chats', 'tags_weight_reactions')
    op.drop_column('chats', 'tags_custom')
    op.drop_column('chats', 'tags_preset')
    op.drop_column('chats', 'tags_enabled')
    op.drop_table('reputation_logs')
    # ### end Alembic commands ###
