"""fix_db_schema_issues

Revision ID: b5070685a23b
Revises: 4fca56dde505
Create Date: 2026-01-25 02:13:43.712025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5070685a23b'
down_revision: Union[str, Sequence[str], None] = '4fca56dde505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chat_trust_history', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'chat_trust_history', 'chats', ['chat_id'], ['id'])
    op.create_index(op.f('ix_triggers_key_phrase'), 'triggers', ['key_phrase'], unique=False)
    op.create_foreign_key(None, 'triggers', 'users', ['created_by'], ['id'])
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_foreign_key(None, 'warns', 'users', ['admin_id'], ['id'])
    op.create_foreign_key(None, 'warns', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warns', type_='foreignkey')
    op.drop_constraint(None, 'warns', type_='foreignkey')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_constraint(None, 'triggers', type_='foreignkey')
    op.drop_index(op.f('ix_triggers_key_phrase'), table_name='triggers')
    op.drop_constraint(None, 'chat_trust_history', type_='foreignkey')
    op.drop_constraint(None, 'chat_trust_history', type_='foreignkey')
    # ### end Alembic commands ###
