"""initial

Revision ID: c9a278958f56
Revises: 
Create Date: 2025-12-28 05:16:38.253692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9a278958f56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('admins_only_add', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('language_code', sa.String(length=10), server_default='ru', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('key_phrase', sa.Text(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('match_type', sa.Enum('EXACT', 'CONTAINS', 'REGEXP', name='match_type_enum'), nullable=False),
    sa.Column('is_case_sensitive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('access_level', sa.Enum('ALL', 'ADMINS', 'OWNER', name='access_level_enum'), nullable=False),
    sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triggers_chat_id'), 'triggers', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triggers_chat_id'), table_name='triggers')
    op.drop_table('triggers')
    op.drop_table('chats')
    # ### end Alembic commands ###
