"""Add timezone, module_triggers, module_moderation to chats; add is_template to triggers; create chat_variables table

Revision ID: d7f98928cb5c
Revises: edef1d13982f
Create Date: 2026-01-17 19:08:10.240790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f98928cb5c'
down_revision: Union[str, Sequence[str], None] = 'edef1d13982f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_variables',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'key')
    )
    op.add_column('chats', sa.Column('timezone', sa.String(), server_default='UTC', nullable=False))
    op.add_column('chats', sa.Column('module_triggers', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('chats', sa.Column('module_moderation', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('triggers', sa.Column('is_template', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('triggers', 'is_template')
    op.drop_column('chats', 'module_moderation')
    op.drop_column('chats', 'module_triggers')
    op.drop_column('chats', 'timezone')
    op.drop_table('chat_variables')
    # ### end Alembic commands ###
