"""add captcha_max_attempts and captcha_ban_duration

Revision ID: e0b48146dc10
Revises: a1b2c3d4e5f6
Create Date: 2026-02-21 14:29:59.574795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0b48146dc10'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('captcha_max_attempts', sa.Integer(), server_default='3', nullable=False))
    op.add_column('chats', sa.Column('captcha_ban_duration', sa.Integer(), server_default='259200', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'captcha_ban_duration')
    op.drop_column('chats', 'captcha_max_attempts')
    # ### end Alembic commands ###
