"""chat trust reputation counters

Revision ID: ecbb12839e31
Revises: e7a1b2c3d4f5
Create Date: 2026-07-31 23:51:48.313501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecbb12839e31'
down_revision: Union[str, Sequence[str], None] = 'e7a1b2c3d4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('moderation_safe_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('chats', sa.Column('moderation_false_positive_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('chats', sa.Column('trust_auto_granted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###
    op.create_index("ix_user_chats_chat_id", "user_chats", ["chat_id"])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_user_chats_chat_id", table_name="user_chats")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'trust_auto_granted')
    op.drop_column('chats', 'moderation_false_positive_count')
    op.drop_column('chats', 'moderation_safe_streak')
    # ### end Alembic commands ###
