"""add has_passed_captcha to user

Revision ID: edef1d13982f
Revises: 811b12267c6e
Create Date: 2026-01-15 21:41:09.953311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edef1d13982f'
down_revision: Union[str, Sequence[str], None] = '811b12267c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_passed_captcha', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_passed_captcha')
    # ### end Alembic commands ###
