"""add_daily_stats

Revision ID: f01e7ebb30cb
Revises: 65947289ff05
Create Date: 2026-01-12 00:05:48.327252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01e7ebb30cb'
down_revision: Union[str, Sequence[str], None] = '65947289ff05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stats',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('messages_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('triggers_count', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_stats')
    # ### end Alembic commands ###
