"""add_gban_enabled_to_chat

Revision ID: f2159545dbbe
Revises: 7c452372538e
Create Date: 2026-01-22 22:22:47.429763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2159545dbbe'
down_revision: Union[str, Sequence[str], None] = '7c452372538e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('gban_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'gban_enabled')
    # ### end Alembic commands ###
